openapi: 3.0.3
info:
  title: Retro Video Game Exchange API
  description: API for trading used retro video games
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string
        status:
          type: integer

    Link:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
        method:
          type: string

    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        streetAddress:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'

    Game:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        publisher:
          type: string
        yearPublished:
          type: integer
        system:
          type: string
        condition:
          type: string
          enum: [mint, good, fair, poor]
        previousOwners:
          type: integer
        ownerId:
          type: string
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'

security:
  - bearerAuth: []

paths:

  /auth/register:
    post:
      summary: Register a new user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [name, email, password, streetAddress]
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
                streetAddress:
                  type: string
      responses:
        201:
          description: User registered successfully

  /auth/login:
    post:
      summary: Authenticate user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [email, password]
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        200:
          description: JWT token returned
          content:
            application/json:
              schema:
                properties:
                  token:
                    type: string

  /users/me:
    get:
      summary: Get authenticated user profile
      tags: [Users]
      responses:
        200:
          description: User profile
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'

    put:
      summary: Update authenticated user profile
      tags: [Users]
      requestBody:
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                streetAddress:
                  type: string
      responses:
        200:
          description: Updated user profile

  /games:
    get:
      summary: Search all games
      tags: [Games]
      parameters:
        - in: query
          name: name
          schema:
            type: string
        - in: query
          name: system
          schema:
            type: string
      responses:
        200:
          description: List of games
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Game'

    post:
      summary: Add a game for trade
      tags: [Games]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required: [name, publisher, yearPublished, system, condition]
              properties:
                name:
                  type: string
                publisher:
                  type: string
                yearPublished:
                  type: integer
                system:
                  type: string
                condition:
                  type: string
                previousOwners:
                  type: integer
      responses:
        201:
          description: Game created

  /games/{id}:
    get:
      summary: Get game details
      tags: [Games]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Game details

    put:
      summary: Update a game (owner only)
      tags: [Games]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Game'
      responses:
        200:
          description: Game updated

    delete:
      summary: Delete a game (owner only)
      tags: [Games]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Game deleted
